version: "3.7"

services:
  api:
    container_name: rails_sample_api
    stdin_open: true
    tty: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - .:/app
    command: bundle exec puma -C config/puma.rb
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    ports:
      - 6000:6000
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
